### ISSUE TITLE
example of DataFrames data

### ISSUE THREAD

**Issue by iuraiura** [bat/BAT.jl#274]
I want more examples. I want an example of processing DataFrames data.

**Comment by oschulz** [comment]
Did you have a specific statistical application in mind? What kind of model/likelihood would the data be related to? The format (`DataFrame`) or doesn't matter so much, as it's typically easy to convert in-memory, and since BAT.jl requires a user-provided likelihood function.

That being said, we do plan to add explicit forward models to BAT.jl soon, and we'll certainly aim to support formats compatible with Tables.jl for unbinned data..

**Comment by iuraiura** [comment]
Thank you.
