### ISSUE TITLE
Linear Regression with BAT

### ISSUE THREAD

**Issue by pkroenert** [bat/BAT.jl#280]
First and foremost, thank you very much for your work and the package.

I do have experience with **STAN.jl** and **Turing.jl**, and wanted to try out **BAT.jl**.
However, I fail to understand the syntax to define 'likelihoods' and 'priors'.

In the previous mentioned Packages, one can define the distribution of a parameter with the convenient tilde-syntax.

The following code, shows how one could implement the posterior for a simple linear regression in **Turing**.
Would you help me to translate it to the BAT-syntax?

Lets assume one uses the Packages:
```
using Turing
using Distributions
```
and defines the posterior to be:
```
@model function posterior(x, y, yerror)

    # define prior probabilities for the two unknown parameters
    intercept ~ Normal(0, 1)
    slope ~ Normal(0, 1)

    # define the function which should be able to describe the data
    mu = slope * x .+ intercept

    # the likelihood function is assumed to me a multivariate Normal distribution
    y ~ MvNormal(mu, yerror)
end
```

**Comment by oschulz** [comment]
Hi @PToTheK,

thanks for your kind words!

While BAT.jl is a high-level package in principle (wrapping different algorithms for sampling, integration, etc. under a common API), it is a lower level package than Turing.jl, since it doesn't offer a DSL for models in the STAN and Turing fashion. BAT.jl requires (on purpose) a clear separation of prior and likelihood. However, ValueShapes.jl (developed in close coordination with BAT.jl) provides a convenient way to write a priors as a `ValueShapes.NamedTupleDist` (just with equal signs instead of a tilde). The likelihood, in BAT, is not just the "noise" at the end of a forward model, but the probability of the observed data under the whole model, given a set of parameter values. While the prior, in the Bayesian sense, should represent prior knowledge that is independent of the data.

The BAT way of doing your example would be

```julia
using BAT, Distributions, ValueShapes, Parameters, Plots

prior = NamedTupleDist(
    intercept = Normal(0, 1),
    slope = Normal(0, 1)
)

function likelihood(x::AbstractVector{<:Real}, y::AbstractVector{<:Real}, yerror::AbstractVector{<:Real})
     v::NamedTuple -> let
        @unpack intercept, slope = v
        mu = slope .* x .+ intercept
        log_likelihood = logpdf(MvNormal(mu, yerror), y)
        return (logval = log_likelihood,) # To explicitly mark this as a log-value
    end
end

# Generate some mock data:
v_true = (intercept = -0.4, slope = 2)
x = [1, 2, 3, 4, 5]
yerror = fill(0.2, length(x))
y_dist = MvNormal(v_true.slope .* x .+ v_true.intercept, yerror)
y = rand(y_dist)

# Create posterior density:
posterior = PosteriorDensity(likelihood(x, y, yerror), prior)

# Try out the posterior at random parameters drawn from prior:
v_guess = rand(prior, ())
log_posterior_at_v_guess = logvalof(posterior)(v_guess)

# Sample the posterior:
smpls = bat_sample(posterior, MCMCSampling(mcalg = HamiltonianMC())).result

# Show a summary:
display(SampledDensity(posterior, smpls))

# Plot samples:
plot(smpls)
```

We will add support for explicit forward models soon (BAT.jl v2.1 of v2.2), which with also integrate BAT.jl with MGVI.jl. This will not a DSL, but consist of a function that returns an "expectation" and a second function that describes the "noise" be turning the "expectation" into a distribution. We do have several nice improvements coming up soon in BAT.jl v2.1 in general.

**Comment by PToTheK** [comment]
Hello @oschulz,
I highly appreciate your answer. Thank you very much!

I'am very interested in how your package determines the `global_mode`.
How well does that work for multimodal posterior distributions?

Best regards!

**Comment by oschulz** [comment]
> I'am very interested in how your package determines the global_mode.

BAT.jl can find the mode based on the sample with the highest value, or run an optimizer (possibly starting at the sample with the highest value). But for multi-modal posteriors, you're always going to end up in one of the modes. We have some internal functions for finding multiple modes in marginalizations (we should add a proper public API for that), but not for the full posterior so far.

The new (and still experimental) `BAT.PartitionedSampling` will try to split the space to separate modes, but we don't have per-partition mode-finding implemented yet.
